//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelEntities : DbContext
    {
        public TravelEntities()
            : base("name=TravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<DonationDetail> DonationDetail { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Travel_Notes> Travel_Notes { get; set; }
        public virtual DbSet<Travel_Places> Travel_Places { get; set; }
        public virtual DbSet<User_Ship> User_Ship { get; set; }
    }
}
