//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Places
    {
        public Nullable<System.Guid> Id_ { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Info { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Statue { get; set; }
        public bool Deleted { get; set; }
    }
}
